### create
POST http://localhost:8080/v1/diaries
Content-Type: application/json

{
  "author": "이희찬",
  "title": "spring 공부",
  "content": "API 테스트해보기"
}

### find all
GET http://localhost:8080/v1/diaries

### find by id
GET http://localhost:8080/v1/diaries/1

### update
PUT http://localhost:8080/v1/diaries/1
Content-Type: application/json

{
  "title": "nodejs 공부",
  "content": "node란 무엇일까"
}

### update status
PATCH http://localhost:8080/v1/diaries/2

### delete
DELETE http://localhost:8080/v1/diaries/3
